### ISSUE TITLE
Is `upload.gtpl` template file missing?

### ISSUE THREAD

**Issue by choonkeat** [archeons/imageupload#1]
Trying to visit a url like `http://localhost:8080/upload/doZPJTWUly1SIf3W_resized.jpg` gives error

NOTE: I had to change `main()` to this instead

``` go
http.HandleFunc("/upload/", upload)
http.ListenAndServe(":8080", nil)
```

**Comment by archeons** [comment]
That is only an example to download the image, as you have mentioned the testing can be done in main.

The main functionality has no issue and are able to download image from the URL.
